config/routes.rb
SampleApp::Application.routes.draw do

  match 'users/destroy', to: 'users#destroy', via: :post
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
      
  root to: 'static_pages#home'

  match '/signup',  to: 'users#new', via: :get
  match '/signin',  to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/help',    to: 'static_pages#help', via: :get
  match '/about',   to: 'static_pages#about', via: :get
  match '/contact', to: 'static_pages#contact', via: :get

  match 'users/search_users', to: 'users#search', via: :post

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <b>Chatter</b>
    made by Brandon Laidig, Brady Carey, Wei Shao, Maxwell Zhou, I-Fan Huang
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">

<div class="container">

    <%= link_to "Chatter", root_path, id: "logo" %>

      <nav>
<%= link_to image_tag("logo.png", alt: "Rails", id: "chatlogo")%>
       <%= form_tag(users_path, :method => "get", class: "navbar-form", id: "search-form") do %>
        <div class="container">
        <%=submit_tag "Search", :class => "btn", :class => "icon-search", id: "search-button"%>
        <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Users", id: "search-users" %>
        <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
        <%end%>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown", id: "account">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%="Welcome to Chatter! - Connect With Friends Now!"%></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>

    <br></br>

    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%=yield%>
      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>